import TerminalConfiguration from "../../../assets/config/developer_data/terminalconfiguration";
export const HelpUser = [TerminalConfiguration.help];
export const WhoamI = [TerminalConfiguration.whoami];
export const EducationQualifications  = [TerminalConfiguration.education];
export const Skills = [TerminalConfiguration.skills];
export const Publications = [TerminalConfiguration.publications];
export const Blog = [TerminalConfiguration.blogs];
export const Github = [TerminalConfiguration.github];
export const Linkedin = [TerminalConfiguration.LinkedIn];
export const Contact = [TerminalConfiguration.contact];
export const Experience = [TerminalConfiguration.experience];
export const Projects = [TerminalConfiguration.projects];
export const ls = [TerminalConfiguration.ls];